name: verify

on: [push, pull_request]

jobs:
  verify-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Count number of changes
      run: |
        python tests/test_infojson.py
