name: verify

on: [push, pull_request]

jobs:
  verify-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Count number of changes
      run: |
        chmod +x tests/count_last_changes.sh
        bash tests/count_last_changes.sh